### ISSUE TITLE
Submit issue if entering height and no weight

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#24]
![Screenshot_20230905_103918_EmCare dev](https://github.com/WorldHealthOrganization/smart-emcare-cmr/assets/122801361/1c5ceae6-69f5-4bdf-8e4a-23891636543a)

**Comment by ppanchal-argus** [comment]
@magp18 
It's a structuremap issue with stacktrace:

**org.hl7.fhir.exceptions.FHIRException: No matches found for rule 'emcareobservationemcareb6de07'. Reference found in https://fhir.dk.swisstph-mis.ch/matchbox/fhir/StructureMap/emcare.b6.measurements**
2023-09-11 05:00:22.272   907-907   System.err              com.argusoft.who.emcare.debug        W  	at org.hl7.fhir.r4.utils.StructureMapUtilities.resolveGroupReference(StructureMapUtilities.java:1688)
2023-09-11 05:00:22.272   907-907   System.err              com.argusoft.who.emcare.debug        W  	at org.hl7.fhir.r4.utils.StructureMapUtilities.executeDependency(StructureMapUtilities.java:1445)

@kaledip can update with L3 label, looks like a simple structuremap issue. @magp18 Feel free to let me know if you still face any difficulties after it!

**Comment by kaledip** [comment]
Retested and can be closed
